#!/bin/bash

function az_login {
   export AZCOPY_AUTO_LOGIN_TYPE=MSI;
   if ! command az > /dev/null; then exit 1; else az login --identity; fi
}

function az_passph {
   echo $(az keyvault secret show --id "{{VAULT_URL}}$1" --query 'value');
}

function apache2_backup {
   for DIR in $APACHE2_LXC_DIR; do 
      cp -R "/opt/$DIR" "$BACKUP_DIR/files/"; 
      tar -zcvf "$BACKUP_DIR/$DIR$CDATE.tar.gz" "$BACKUP_DIR/files";
      OUT_FILES+="$BACKUP_DIR/$DIR$CDATE.tar.gz ";
   done
}

function mysql_backup {
   PASSWD=$(az_passph "{{MYSQL_PASSPH}}"|sed 's/\"//g');
   i=0;
   for CONT in $MYSQL_LXC_NAME; do 
      DBDUMP_NAME="mysql_dbdump_c$i";
      docker exec -it $CONT mysqldump -u 'root' "-p$PASSWD" --all-databases > /backup/$DBDUMP_NAME$CDATE.sql;
      OUT_FILES+="$BACKUP_DIR/$DBDUMP_NAME$CDATE.sql ";
      i=$((i+1));
   done
}

function hash_file {
   for FILE in $OUT_FILES; do 
      md5sum "$FILE" >> "$FILE.hash";
      OUT_FILES+="$FILE.hash ";
   done
}

function encrypt_file {
   pass="$(az_passph "{{GPG_PASSPH}}")";
   for FILE in $OUT_FILES; do 
      if [[ $FILE != *'.hash'* ]]; then
         gpg --symmetric --batch --passphrase "$pass" --cipher-algo AES256 $FILE;
         OUT_FILES+="$FILE.gpg ";
      fi
   done
}

function az_upload {
   for FILE in $OUT_FILES; do
      if [[ $FILE = *'.gpg'* || $FILE = *'.hash'* ]]; then
         azcopy copy "$FILE" "{{BLOB_URL}}";
      fi
   done
}

BACKUP_DIR="{{BACKUP_DIR}}";
CDATE=$(date +'_%F_%T');
OUT_FILES="";
MYSQL_LXC_DIR="{% if mysql_container == 1 %}{{"mysql"}}{% endif %}";
APACHE2_LXC_DIR="{% if apache2_container == 1 %}{{"apache2"}}{% endif %}";
CONF_DIR=$MYSQL_LXC_DIR$APACHE2_LXC_DIR;
MYSQL_LXC_NAME="{% for con in mysql_lxc %}{{con.name}}{%endfor%}";
APACHE2_LXC_NAME="{% for con in apache2_lxc %}{{con.name}}{%endfor%}";

az_login;
apache2_backup;
mysql_backup;
hash_file;
encrypt_file;
az_upload;
