---
- community.general.sudoers:
    name: "{{ user.name }}"
    user: "{{ user.name }}"
    #group: "{{ user.name }}"
    state: present
    nopassword: "{{ user.nopasswd }}"
    commands: "{{ user.commands }}"
    validation: required
