---
- name: 'Create user accounts.'
  ansible.builtin.user:
    name: "{{ item.name }}"
    shell: '/bin/bash'
    create_home: true
  loop: "{{ user_accounts }}"

- name: 'Create ssh directory.'
  ansible.builtin.file:
    path: "/home/{{ item.name }}/.ssh/"
    state: directory
    mode: '0600'
    owner: "{{ item.name }}"
    group: "{{ item.name }}"
  loop: "{{ user_accounts }}"

- name: 'Create authorized_keys file.'
  ansible.builtin.file:
    path: "/home/{{ item.name }}/.ssh/authorized_keys"
    state: touch
    mode: '0600'
    owner: "{{ item.name }}"
    group: "{{ item.name }}"
  loop: "{{ user_accounts }}"

- name: 'Add ssh keys.'
  include_tasks:
    file: "./ssh_copy.yml"
  loop: "{{ user_accounts }}"
  loop_control:
    loop_var: 'user'

- name: 'Add to sudoers.'
  include_tasks:
    file: './add_sudoers.yml'
  when: 'user.sudoers == 1'
  loop: "{{ user_accounts }}"
  loop_control:
    loop_var: 'user'
