---

- name: 'Enable AZ managed identity login.'
  vars:
    cmd_o: -1
  shell: 'export AZCOPY_AUTO_LOGIN_TYPE=MSI'
  register: cmd_o
  failed_when: cmd_o.rc > 0

- name: 'Make backup directory.'
  ansible.builtin.file:
    path:  "{{BACKUP_DIR}}"
    state: 'directory'

- name: 'Make backup/files directory.'
  ansible.builtin.file:
    path: "{{BACKUP_DIR}}/files"
    state: 'directory'

- name: 'Copy backup script.'
  ansible.builtin.template:
    src: 'make_backup'
    dest: '/opt'
    mode: '+x'

- name: 'Add cron job.'
  ansible.builtin.cron:
    name: 'make backup'
    minute: 0
    hour: 0
    day: '*'
    month: '*'
    state: 'present'
    job: 'sh /opt/make_backup'
