#!/bin/sh

BACKUP_DIR="/backup"
BACKUP_EXT=".sql"
CONF_DIR="apache mysql"

# Compress each config directory inside $BACKUP_DIR
for DIR in $CONF_DIR; do
   tar -zcvf $BACKUP_DIR/$DIR$BACKUP_EXT /opt/$DIR
done

# Copy recursively compressed tar files
azcopy copy $BACKUP_DIR '{{ sas_url }}' --recursive=true
